# Generated by Django 4.2.3 on 2023-07-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E5Championship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='E5Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='E5Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5championship')),
            ],
        ),
        migrations.AddField(
            model_name='e5championship',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5country'),
        ),
    ]
