# Generated by Django 4.2.3 on 2023-08-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5season',
            name='url',
            field=models.URLField(),
        ),
    ]
