# Generated by Django 4.2.3 on 2023-07-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='E5Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('League', 'League'), ('Cup', 'Cup')], max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5country')),
            ],
        ),
    ]
