# Generated by Django 4.2.3 on 2023-07-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_e5country_name_e5competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5Championship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5country')),
            ],
        ),
        migrations.CreateModel(
            name='E5Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5championship')),
            ],
        ),
        migrations.DeleteModel(
            name='E5Competition',
        ),
    ]
