# Generated by Django 4.2.3 on 2023-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_e5season'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5championship',
            name='seasons',
            field=models.ManyToManyField(to='Website.e5season'),
        ),
    ]
