# Generated by Django 4.2.3 on 2023-08-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_e5season_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueTable',
            new_name='E5LeagueTable',
        ),
    ]
