# Generated by Django 4.2.3 on 2023-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_e5championship_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5season',
            name='squads',
            field=models.IntegerField(default=0),
        ),
    ]
