# Generated by Django 4.2.3 on 2023-08-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_rename_leaguetable_e5leaguetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e5leaguetable',
            options={'verbose_name': 'League Table', 'verbose_name_plural': 'League Tables'},
        ),
        migrations.RemoveField(
            model_name='e5leaguetable',
            name='league',
        ),
        migrations.AddField(
            model_name='e5leaguetable',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
