# Generated by Django 4.2.3 on 2023-07-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_e5season_squads'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5season',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
