# Generated by Django 4.2.3 on 2023-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_e5season_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5team',
            name='seasons',
            field=models.ManyToManyField(to='Website.e5season'),
        ),
    ]
