# Generated by Django 4.2.3 on 2023-08-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_e5leaguetable_iframe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5leaguetable',
            name='iframe_url',
            field=models.URLField(max_length=500),
        ),
    ]
