# Generated by Django 4.2.3 on 2023-07-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_e5team_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e5championship',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='e5team',
            name='seasons',
        ),
        migrations.AddField(
            model_name='e5season',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.e5championship'),
        ),
    ]
