# Generated by Django 4.2.3 on 2023-08-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_e5team_e5league_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5team',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.e5season'),
        ),
    ]
