# Generated by Django 4.2.3 on 2023-07-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_remove_e5championship_seasons_remove_e5team_seasons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e5team',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='e5team',
            name='gender',
        ),
        migrations.AddField(
            model_name='e5team',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.e5season'),
        ),
    ]
