# Generated by Django 4.2.3 on 2023-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_e5team_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5team',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
