# Generated by Django 4.2.3 on 2023-07-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_remove_e5team_championship_remove_e5team_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5country',
            name='parse_country',
            field=models.BooleanField(default=False),
        ),
    ]
