# Generated by Django 4.2.3 on 2023-07-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_e5country_parse_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=40)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='Website.e5team')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5championship')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='Website.e5team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
        ),
    ]
