# Generated by Django 4.2.3 on 2023-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_e5team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5team',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
