# Generated by Django 4.2.3 on 2023-08-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_alter_e5team_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e5team',
            name='slug',
        ),
    ]
