# Generated by Django 4.2.3 on 2023-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_e5match'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5country',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
