# Generated by Django 4.2.3 on 2023-08-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_remove_e5team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5TeamRanking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ranking', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_drawn', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('goals_difference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5team')),
            ],
            options={
                'verbose_name': 'Team Ranking',
                'verbose_name_plural': 'Team Rankings',
            },
        ),
    ]
