# Generated by Django 4.2.3 on 2023-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_e5country_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5championship',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='e5team',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
