# Generated by Django 4.2.3 on 2023-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_e5championship_logo_e5team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5season',
            name='squads',
            field=models.IntegerField(default=None),
        ),
    ]
