# Generated by Django 4.2.3 on 2023-08-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_e5bttsiframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5BttsIframes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('btts_url', models.URLField(max_length=500)),
                ('btts_1h_url', models.URLField(max_length=500)),
                ('btts_2h_url', models.URLField(max_length=500)),
                ('btts_25_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'BTTS Iframe',
                'verbose_name_plural': 'BTTS Iframes',
            },
        ),
        migrations.DeleteModel(
            name='E5BttsIframe',
        ),
    ]
