# Generated by Django 4.2.3 on 2023-08-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_e5season_squads'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5TeamStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goals', models.IntegerField()),
                ('xg', models.FloatField(blank=True, null=True)),
                ('shots', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('corners', models.IntegerField(blank=True, null=True)),
                ('tackles', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('offsides', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='e5season',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='e5match',
            name='at_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_stats', to='Website.e5teamstats'),
        ),
        migrations.AddField(
            model_name='e5match',
            name='ht_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ht_stats', to='Website.e5teamstats'),
        ),
    ]
