# Generated by Django 4.2.3 on 2023-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_e5bttsiframes_delete_e5bttsiframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5bttsiframes',
            name='btts_bh_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
