# Generated by Django 4.2.3 on 2023-08-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_remove_e5bttsiframes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5Over05GoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('over_05_goals_url', models.URLField(max_length=500)),
                ('over_05_goals_1h_url', models.URLField(max_length=500)),
                ('over_05_goals_2h_url', models.URLField(max_length=500)),
                ('over_05_goals_bh_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Over 0.5 Goals Iframe',
                'verbose_name_plural': 'Over 0.5 Goals Iframes',
            },
        ),
    ]
