# Generated by Django 4.2.3 on 2023-08-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_e5over05goalsiframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5Over35GoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('over_35_goals_url', models.URLField(max_length=500)),
                ('over_35_goals_1h_url', models.URLField(max_length=500)),
                ('over_35_goals_2h_url', models.URLField(max_length=500)),
                ('over_35_goals_bh_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Over 3.5 Goals Iframe',
                'verbose_name_plural': 'Over 3.5 Goals Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5Over25GoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('over_25_goals_url', models.URLField(max_length=500)),
                ('over_25_goals_1h_url', models.URLField(max_length=500)),
                ('over_25_goals_2h_url', models.URLField(max_length=500)),
                ('over_25_goals_bh_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Over 2.5 Goals Iframe',
                'verbose_name_plural': 'Over 2.5 Goals Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5Over15GoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('over_15_goals_url', models.URLField(max_length=500)),
                ('over_15_goals_1h_url', models.URLField(max_length=500)),
                ('over_15_goals_2h_url', models.URLField(max_length=500)),
                ('over_15_goals_bh_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Over 1.5 Goals Iframe',
                'verbose_name_plural': 'Over 1.5 Goals Iframes',
            },
        ),
    ]
