# Generated by Django 4.2.3 on 2023-08-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_e5cardsiframes'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5Over05GoalsStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_matches_played', models.IntegerField()),
                ('home_over_05_goals', models.IntegerField()),
                ('home_over_05_goals_percent', models.CharField(max_length=10)),
                ('home_over_05_goals_1h', models.IntegerField()),
                ('home_over_05_goals_1h_percent', models.CharField(max_length=10)),
                ('home_over_05_goals_2h', models.IntegerField()),
                ('home_over_05_goals_2h_percent', models.CharField(max_length=10)),
                ('home_over_05_goals_bh', models.IntegerField()),
                ('home_over_05_goals_bh_percent', models.CharField(max_length=10)),
                ('away_matches_played', models.IntegerField()),
                ('away_over_05_goals', models.IntegerField()),
                ('away_over_05_goals_percent', models.CharField(max_length=10)),
                ('away_over_05_goals_1h', models.IntegerField()),
                ('away_over_05_goals_1h_percent', models.CharField(max_length=10)),
                ('away_over_05_goals_2h', models.IntegerField()),
                ('away_over_05_goals_2h_percent', models.CharField(max_length=10)),
                ('away_over_05_goals_bh', models.IntegerField()),
                ('away_over_05_goals_bh_percent', models.CharField(max_length=10)),
                ('overall_matches_played', models.IntegerField()),
                ('overall_over_05_goals', models.IntegerField()),
                ('overall_over_05_goals_percent', models.CharField(max_length=10)),
                ('overall_over_05_goals_1h', models.IntegerField()),
                ('overall_over_05_goals_1h_percent', models.CharField(max_length=10)),
                ('overall_over_05_goals_2h', models.IntegerField()),
                ('overall_over_05_goals_2h_percent', models.CharField(max_length=10)),
                ('overall_over_05_goals_bh', models.IntegerField()),
                ('overall_over_05_goals_bh_percent', models.CharField(max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5team')),
            ],
            options={
                'verbose_name': 'Over 0.5 Goals Stats',
                'verbose_name_plural': 'Over 0.5 Goals Stats',
            },
        ),
    ]
