# Generated by Django 4.2.3 on 2023-08-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_alter_e5bttsiframes_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5team',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
