# Generated by Django 4.2.3 on 2023-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0026_e5team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e5team',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
