# Generated by Django 4.2.3 on 2023-08-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0027_alter_e5team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5WinDrawLossPercentageIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Win Draw Loss Percentage Iframe',
                'verbose_name_plural': 'Win Draw Loss Percentage Iframes',
            },
        ),
    ]
