# Generated by Django 4.2.3 on 2023-08-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0028_e5windrawlosspercentageiframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5WonBothHalfIframes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('won_both_half_url', models.URLField(max_length=500)),
                ('lost_both_half_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Won Both Half Iframe',
                'verbose_name_plural': 'Won Both Half Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5ScoredBothHalfIframes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scored_both_half_url', models.URLField(max_length=500)),
                ('conceded_both_half_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Scored Both Half Iframe',
                'verbose_name_plural': 'Scored Both Half Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5HalfTimeFullTimeIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Half Time Full Time Iframe',
                'verbose_name_plural': 'Half Time Full Time Iframes',
            },
        ),
    ]
