# Generated by Django 4.2.3 on 2023-08-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0029_e5wonbothhalfiframes_e5scoredbothhalfiframes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5WonToNilIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('won_to_nil_url', models.URLField(max_length=500)),
                ('lost_to_nil_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Won To Nil Iframe',
                'verbose_name_plural': 'Won To Nil Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5WinLossMarginIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winning_margins_url', models.URLField(max_length=500)),
                ('losing_margins_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Win Loss Margin Iframe',
                'verbose_name_plural': 'Win Loss Margin Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5ScoredFirstIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scored_first_url', models.URLField(max_length=500)),
                ('conceded_first_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Scored First Iframe',
                'verbose_name_plural': 'Scored First Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5RescuedPointsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Rescued Points Iframe',
                'verbose_name_plural': 'Rescued Points Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5LateGoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Late Goals Iframe',
                'verbose_name_plural': 'Late Goals Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5EarlyGoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Early Goals Iframe',
                'verbose_name_plural': 'Early Goals Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5CleanSheetIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clean_sheet_url', models.URLField(max_length=500)),
                ('failed_to_score_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Clean Sheet Iframe',
                'verbose_name_plural': 'Clean Sheet Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5AverageTeamGoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Average Team Goals Iframe',
                'verbose_name_plural': 'Average Team Goals Iframes',
            },
        ),
        migrations.CreateModel(
            name='E5Average1stGoalTimeIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': 'Average 1st Goal Time Iframe',
                'verbose_name_plural': 'Average 1st Goal Time Iframes',
            },
        ),
        migrations.CreateModel(
            name='E51st2ndHalfGoalsIframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_1st_2nd_half_goals_url', models.URLField(max_length=500)),
                ('home_1st_2nd_half_goals_url', models.URLField(max_length=500)),
                ('away_1st_2nd_half_goals_url', models.URLField(max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.e5season')),
            ],
            options={
                'verbose_name': '1st 2nd Half Goals Iframe',
                'verbose_name_plural': '1st 2nd Half Goals Iframes',
            },
        ),
    ]
