# Generated by Django 4.2.3 on 2023-09-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0031_e5wontonilstats_e5wonbothhalfstats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_loose_by_1',
            new_name='away_games_loose_by_1',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_loose_by_2',
            new_name='away_games_loose_by_2',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_loose_by_3',
            new_name='away_games_loose_by_3',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_loose_by_4_or_more',
            new_name='away_games_loose_by_4_or_more',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_won_by_1',
            new_name='away_games_won_by_1',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_won_by_2',
            new_name='away_games_won_by_2',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_won_by_3',
            new_name='away_games_won_by_3',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_won_by_4_or_more',
            new_name='away_games_won_by_4_or_more',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_loose_by_1',
            new_name='home_games_loose_by_1',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_loose_by_2',
            new_name='home_games_loose_by_2',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_loose_by_3',
            new_name='home_games_loose_by_3',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_loose_by_4_or_more',
            new_name='home_games_loose_by_4_or_more',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_won_by_1',
            new_name='home_games_won_by_1',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_won_by_2',
            new_name='home_games_won_by_2',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_won_by_3',
            new_name='home_games_won_by_3',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_won_by_4_or_more',
            new_name='home_games_won_by_4_or_more',
        ),
    ]
