# Generated by Django 4.2.3 on 2023-09-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0032_rename_away_loose_by_1_e5winlossmarginstats_away_games_loose_by_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='away_games_lost',
            new_name='away_games_loose',
        ),
        migrations.RenameField(
            model_name='e5winlossmarginstats',
            old_name='home_games_lost',
            new_name='home_games_loose',
        ),
    ]
