# Generated by Django 4.2.3 on 2023-09-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0033_rename_away_games_lost_e5winlossmarginstats_away_games_loose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='E5Fixture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('kickoff_time', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='Website.e5team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='Website.e5team')),
            ],
        ),
    ]
