# Generated by Django 4.2.3 on 2023-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0034_e5fixture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e5fixture',
            options={'verbose_name': 'Fixture', 'verbose_name_plural': 'Fixtures'},
        ),
        migrations.AlterField(
            model_name='e5fixture',
            name='date',
            field=models.DateField(),
        ),
    ]
