# Generated by Django 4.2.3 on 2023-09-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0036_e5fixture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='e5matchcornerstats',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='e5teamcornerstats',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
